
version: 1
disable_existing_loggers: true
incremental : False

filters:
    info_filter:
        () : loggers.filters.InfoFilter
    error_filter :
        () : loggers.filters.ErrorFilter
    debug_filter :
        () : loggers.filters.DebugFilter
    critical_filter :
        () : loggers.filters.CriticalFilter
    warning_filter :
        () : loggers.filters.WarningFilter
formatters:
    standard:
        format: "%(asctime)s|%(levelname)s|%(name)s|%(message)s"
    error:
        format: "%(asctime)s|%(levelname)s|<PID %(process)d:%(processName)s>|%(name)s.%(funcName)s(%(lineno)d)|%(message)s"

handlers:

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout
        filters: [debug_filter]

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: loggers/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        filters: [info_filter]

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: loggers/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        filters: [error_filter]

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: loggers/logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        filters: [debug_filter]

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: loggers/logs/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        filters: [critical_filter]

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: loggers/logs/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        filters: [warning_filter]
        
    error_console:
        class: logging.StreamHandler
        level: ERROR
        formatter: error
        stream: ext://sys.stderr
        filters: [error_filter]

root:
    level: NOTSET
    handlers: [console, error_console]
    propogate: no

loggers:
    __main__:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: no

    Configuration.config:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: no

    Factory.FtpLoader:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: no

    Terminal :
        level: DEBUG
        handlers: [console, error_console]
        propogate: no