URL :
  MOT_FTP_SITE : ftp://gtfs.mot.gov.il/

FILES : 
  TRANSPORTATION : israel-public-transportation.zip

WS :
  DOWNLOAD : \\ntgisfs\MAPINFO\spool\MOT
  EXTRACTED : \\ntgisfs\MAPINFO\spool\MOT\MOT_Latest
