URL :
  MOT : gtfs.mot.gov.il

FILES :
  TRANSPORTATION : israel-public-transportation.zip

WS :
  DOWNLOAD : download
  EXTRACTED : extract

DB :
  SDE :
    SERVER : NTSQLSDE12
    INSTANCE : SDE
    USER : sde
    PSWD : sde
