WS :
  DOWNLOAD :
    MOT : download
  EXTRACTED :
    MOT : extract

DB :
  SDE :
    SERVER : NTSQLSDE12
    INSTANCE : SDE
    USER : sde
    PSWD : sde

  MY_SQL :
    HOST : localhost
    USER : louis6
    PWD : dev123

