WS :
  DOWNLOAD :
    MOT : download
  EXTRACTED :
    MOT : extract

DB :
  SDE :
    SERVER : NTSQLSDE12
    INSTANCE : SDE
    USER : sde
    PSWD : sde

  MY_SQL_SDE :
    HOST : localhost
    DB : sde
    USER : louis6
    PSWD : dev123

