WS :
  DOWNLOAD :
    MOT : download
  EXTRACT :
    MOT : extract

DB :
  SDE :
    SERVER : NTSQLSDE12
    INSTANCE : SDE
    USER : sde
    PSWD : sde
    TECH : MSSQL

  MY_SQL_SDE :
    HOST : localhost
    DB : sde
    USER : louis6
    PSWD : dev123
    TECH : MYSQL

  POSTGIS :
    HOST: localhost
    DB: mot
    USER: postgres
    PSWD: dev123
    TECH: POSTGRESQL


