URL :
  - MOT : gtfs.mot.gov.il

FILES :
  MOT :
    israel-public-transportation.zip :
        - NAME : stops.txt
          ITYPE : GEO
          GEO_TYPE : point
          AOI : JERUSALEM
          FILTER_TYPE : within
          RESULT_NAME: stops
          CB:
#            - NAME: filterAlphanum
#              ITYPE : TABLES
#              TABLES:
#                - NAME: stop_times.txt
#                  ITYPE : ALPHA
#                  PATH: extract
#                  JOIN_FIELD: stop_id
#                  FOOD_FIELDS:
#                    - trip_id
#                    - arrival_time
#                    - departure_time
#                    - stop_id
#                    - stop_sequence
#                    - pickup_type
#                    - drop_off_type
#                    - shape_dist_traveled
#                  RESULT_NAME: stops.time
#                  LINKED_TO : stops
#                  CB :
#                    - NAME : DB
#                      ITYPE : DB_CB
#                      INSTANCE : SDE_ALPHANUM
#                      ACTION : insert
#                      TABLE : stop_times
#                      RESULT_NAME: stops.time.db
#                      LINKED_TO: stops.time
#
            - NAME: DB
              ITYPE: DB
              INSTANCE: SDE_GEO
              BEFORE :
                - NAME : UPDATE_TO_FALSE
                  PARAMETERS :
                    - BUSSTOPS_NEW
              MAIN: insertGeo
              AFTER : no
              TABLE: BUSSTOPS_NEW
              RESULT_NAME: stops.geo
              LINKED_TO: stops

        - NAME : shapes.txt
          ITYPE : GEO
          GEO_TYPE: line
          AOI: JERUSALEM
          FILTER_TYPE : within
          RESULT_NAME : shapes
          CB:
            - NAME: filterAlphanum
              ITYPE : TABLES
              TABLES :
                - NAME : trips.txt
                  ITYPE : ALPHA
                  PATH : extract
                  JOIN_FIELD : shape_id
                  RESULT_NAME: shapes.trips
                  LINKED_TO: shapes
                  FOOD_FIELDS :
                    - route_id
                    - service_id
                    - trip_id
                    - trip_headsign
                    - direction_id
            - NAME: DB
              ITYPE: DB
              INSTANCE: POSTGIS
              ACTION: insertGeo
              TABLE: shapes
              RESULT_NAME: stops.time.db
              LINKED_TO: shapes




